source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.10'

gem 'rails', '~> 7.2', '>= 7.2.3.1'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 6.0'
gem 'dartsass-rails', '~> 0.5'
gem 'terser'
gem 'turbo-rails'
gem 'jbuilder', '~> 2.11'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'chartkick', '~> 5.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '~> 4.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
